#!/bin/bash

HOSTNAME=$(hostname -s)

if [ "$PAM_TYPE" = "close_session" ]; then
  RESPONSE=$(curl -X POST http://freepc.private.vki.eu/disconnect/.json -u USER:PASSWD -d "{\"hostname\": \"$HOSTNAME\", \"connection_type\": \"ssh\", \"username\": \"$PAM_USER\"}" -H "Content-Type: application/json" --connect-timeout 5 2> /dev/null)
  CODE=-1
  MSG=""
  if [ -n "$RESPONSE" ]; then
    CODE=$(echo $RESPONSE | /opt/vki/jq ".code")
    MSG=$(echo $RESPONSE | /opt/vki/jq ".content")

    MSG=$(echo $MSG | tr -d '"')
  else
    echo "Time out. The authentication server is not responding."
    echo "Please contact the Computer Center."
    echo " "
    exit 1
  fi
  echo -e $MSG
  echo " "
  exit 0
fi
